version: '3.4'
services:
    manh-web:
        container_name: manh-web
        build: 
            context: ./app
            # target: dev
        command: npm start
        ports:
            - "3000:3000"
        # environment:
        #     NODE_ENV: dev
        #     DATABASE_URL: postgres://postgres:postgres@postgres:5435
        sysctls:
            - net.core.somaxconn=4096  
    manh-nginx:
        image: nginx
        ports: 
            - 8001:80
        container_name: manh-employee-nginx
        depends_on: 
            - manh-web
        volumes: 
            - ./nginx/default.conf:/etc/nginx/nginx.conf 
    # manh-employee-nginx:
    #     container_name: manh-nginx-employee
    #     restart: always
    #     build: 
    #         context: ./nginx
    #     ports: 
    #         - "80:80"
    # postgres:
    #     image: postgres:13.1
    #     ports: 
    #         - "5435:5435"
    #     environment: 
    #         POSTGRES_USER: postgres
    #         POSTGRES_DB: postgres
    #         POSTGRES_PASSWORD: mysecretpassword
        