version: '3.4'
services:
    web:
        build: 
            context: ./app
            target: dev
        command: npm start
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: dev
    nginx:
        restart: always
        build: 
            context: ./nginx
        ports: 
            - "80:80"